name: Build MacOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  MacOS:
    runs-on: macos-latest
    name: MacOS
    strategy:
        fail-fast: false
        matrix:
            build_type: [Debug]
            clang_version: [clang++]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/MacOS_${{matrix.build_type}}_${{matrix.clang_version}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.clang_version}} -DUSE_AVX2=OFF Build
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/MacOS_${{matrix.build_type}}_${{matrix.clang_version}} --config ${{matrix.build_type}}
    - name: Test
      working-directory: ${{github.workspace}}/Build/MacOS_${{matrix.build_type}}_${{matrix.clang_version}}
      run: ./UnitTests
#      run: ctest --output-on-failure
