name: Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Linux
    strategy:
        fail-fast: false
        matrix:
            build_type: [Debug, Release, Distribution, ReleaseASAN, ReleaseUBSAN]

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/Linux_${{matrix.build_type}} -DCMAKE_BUILD_TYPE=${{matrix.build_type}} Build
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/Linux_${{matrix.build_type}} --config ${{matrix.build_type}}
    - name: Test
      working-directory: ${{github.workspace}}/Build/Linux_${{matrix.build_type}}
      run: ctest --output-on-failure
