name: Build and Deploy

on:
  push:
    branches: [ main ]

env:
  EMSCRIPTEN_VERSION: 3.1.62
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: ${{ env.EMSCRIPTEN_VERSION }}

    - name: Verify emsdk
      run: emcc -v

    - name: Setup Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x

    - name: Configure CMake
      run: cmake -S . -B Temp -G "Unix Makefiles" -DTARGET_HELLO_WORLD=OFF -DTARGET_PERFORMANCE_TEST=OFF -DCMAKE_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
      
    - name: Build
      run: cmake --build Temp -j 2
      
    - name: Test
      working-directory: Temp
      run: node UnitTests.js
