name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/Linux_${{env.BUILD_TYPE}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} Build
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/Linux_${{env.BUILD_TYPE}} --config ${{env.BUILD_TYPE}}
    - name: Test
      working-directory: ${{github.workspace}}/Build/Linux_${{env.BUILD_TYPE}}
      run: ctest -C ${{env.BUILD_TYPE}}
  
