name: Check Determinism ARM

env:
    CONVEX_VS_MESH_HASH: '0x485e1d8e739a3c9d'
    RAGDOLL_HASH: '0xc29b4c0ea4cf1876'

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'

jobs:
  check_determinism_arm:
    runs-on: ubuntu-latest
    name: Check Determinism ARM
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: aarch64
          distro: ubuntu_latest
          githubToken: ${{ github.token }}
          install: |
            apt-get update
            apt-get install clang cmake -y
          env: |
            CONVEX_VS_MESH_HASH: '${{ env.CONVEX_VS_MESH_HASH }}'
            RAGDOLL_HASH: '${{ env.RAGDOLL_HASH }}'

          run: |
            echo "Configure cmake"
            cmake -B ./Build/Linux_Distribution -DCMAKE_BUILD_TYPE=Distribution Build -DCROSS_PLATFORM_DETERMINISTIC=ON -DTARGET_VIEWER=OFF -DTARGET_SAMPLES=OFF -DTARGET_HELLO_WORLD=OFF
            echo "Build"
            cmake --build ./Build/Linux_Distribution
            cd ./Build/Linux_Distribution
            echo "Run UnitTests"
            ctest --output-on-failure
            echo "Run ConvexVsMesh"
            ./PerformanceTest -q=LinearCast -t=2 -s=ConvexVsMesh -validate_hash=${CONVEX_VS_MESH_HASH}
            echo "Run Ragdoll"
            ./PerformanceTest -q=LinearCast -t=2 -s=Ragdoll -validate_hash=${RAGDOLL_HASH}