name: Check Determinism ARM

env:
    CONVEX_VS_MESH_HASH: '0x485e1d8e739a3c9d'
    RAGDOLL_HASH: '0xc29b4c0ea4cf1876'

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'

jobs:
  check_determinism_arm:
    runs-on: ubuntu-latest
    name: Check Determinism ARM
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install cross compiler
      run: sudo apt-get install gcc-9-aarch64-linux-gnu gcc-9-multilib g++-9-multilib libstdc++-9-dev-arm64-cross -y
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/Linux_Distribution -DCMAKE_BUILD_TYPE=Distribution -DCMAKE_CXX_COMPILER=clang++ Build -DCROSS_PLATFORM_DETERMINISTIC=ON -DTARGET_VIEWER=OFF -DTARGET_SAMPLES=OFF -DTARGET_HELLO_WORLD=OFF -DTARGET_UNIT_TESTS=ON
    - name: Build
      run: cmake --build ${{github.workspace}}/Build/Linux_Distribution
    - name: Test
      working-directory: ${{github.workspace}}/Build/Linux_Distribution
      run: qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./UnitTests
    - name: Test ConvexVsMesh
      working-directory: ${{github.workspace}}/Build/Linux_Distribution
      run: qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./PerformanceTest -q=LinearCast -t=2 -s=ConvexVsMesh -validate_hash=${CONVEX_VS_MESH_HASH}
    - name: Test Ragdoll
      working-directory: ${{github.workspace}}/Build/Linux_Distribution
      run: qemu-aarch64 -L /usr/aarch64-linux-gnu/ ./PerformanceTest -q=LinearCast -t=2 -s=Ragdoll -validate_hash=${RAGDOLL_HASH}
