name: Determinism Check

env:
    EXPECTED_HASH: '1234'

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'

jobs:
  msvc_cl:
    runs-on: windows-latest
    name: Visual Studio CL Determinism Check

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/Build/VS2022_CL -G "Visual Studio 17 2022" -A x64 Build -DCROSS_PLATFORM_DETERMINISTIC=ON -DTARGET_VIEWER=OFF -DTARGET_SAMPLES=OFF -DTARGET_HELLO_WORLD=OFF -DTARGET_UNIT_TESTS=OFF
    - name: Build
      run: msbuild Build\VS2022_CL\JoltPhysics.sln /property:Configuration=Distribution
    - name: Test ConvexVsMesh
      working-directory: ${{github.workspace}}/Build/VS2022_CL/Distribution
      run: ./PerformanceTest -q=Discrete -t=2 -s=ConvexVsMesh -validate_hash=$env:EXPECTED_HASH
