name: Determinism Check

env:
    EXPECTED_HASH: '1234'

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'Docs/**'
      - '**.md'
      - '**.txt'

jobs:
  msvc_cl:
    runs-on: windows-latest
    name: Visual Studio CL Determinism Check

    steps:
    - name: Test ConvexVsMesh
      working-directory: ${{github.workspace}}/Build/VS2022_CL/Distribution
      run: echo ./PerformanceTest -q=Discrete -t=2 -s=ConvexVsMesh -validate_hash=$env:EXPECTED_HASH $env:EXPECTED_HASH $EXPECTED_HASH %EXPECTED_HASH %EXPECTED_HASH%
